# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "C0lz3vJGgi6vpia/5QTBIKRlNRECW+xYA8swd88NMeYHUapmW+C23UhJ7xMVJlMhxuLUus/l9gnk01DpARmfGNCgCjdoOV2eTPQTEdGqqdXIE6ewhYMvCSc31kena+1HrXZEao3T0TDQdcV310lZOzipC1Nk4RviyRox4BvNdS4I66xiUTjhUp2PeOW7zJsoI3Bt3pZqd6OC9xqeBS3Fd9hKxYv3ynjkITvtkpv4Ra22wBHb0ROl49wYa02goBJ2qxmHT/igItuWfPy8Q+B2wew/mscnkus4+pS/ntfwYnQTeLUEpjH3dKAEl/I8vhsiWFkyc9ymusYz8R4rbZWllWrLkrG2QHvMm414Niw+Lwbe9CO5A1o3bm/xLMDtMPLZ6Rq4L+gx6nJf+5k5QR9HlVEKDnXcg5I0BelS0BUzOCUFGYWLcbAyi6aMkKIKWJi0Qi5S2FBs+faxO7c2iOk1Gb7U/2ZTNbg06J1ixBnsLuxPAWNSYEK0i9Z5i51SqmPLXoCa3vcufL9fsDrkO78fuwLb++N+YV454wx8MFMtL2bUAngBH7J4ju0tcj53m4bifVYxuXcxnAs69JK7EoUhboMH2KDuPLg5gT/3TsgN09fWMa2rG/2dpIyThJ8Sf/ZRzH+uFCXjXZxHRDjD6vD0YOmKHNbxwPBGR5H/JplFsfA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
