# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "C0lz3vJGgi6vpia/5QTBIKRlNRECW+xYA8swd88NMeYHUapmW+C23UhJ7xMVJlMhxuLUus/l9gnk01DpARmfGNCgCjdoOV2eTPQTEdGqqdXIE6ewhYMvCSc31kena+1HrXZEao3T0TDQdcV310lZOzipC1Nk4RviyRox4BvNdS4I66xiUTjhUp2PeOW7zJsoI3Bt3pZqd6OC9xqeBS3Fd9hKxYv3ynjkITvtkpv4Ra22wBHb0ROl49wYa02goBJ2qxmHT/igItuWfPy8Q+B2wew/mscnkus4+pS/ntfwYnQTeLUEpjH3dKAEl/I8vhsiWFkyc9ymusYz8R4rbZWllWrLkrG2QHvMm414Niw+Lwbe9CO5A1o3bm/xLMDtMPLZ6Rq4L+gx6nJf+5k5QR9HlVEKDnXcg5I0BelS0BUzOCUFGYWLcbAyi6aMkKIKWJi0Qi5S2FBs+faxO7c2iOk1Gb7U/2ZTNbg06J1ixBnsLuxPAWNSYEK0i9Z5i51SqmPLXoCa3vcufL9fsDrkO78fuwLb++N+YV454wx8MFMtL2bUAngBH7J4ju0tcj53m4bifVYxuXcxnAs69JK7EoUhboMH2KDuPLg5gT/3TsgN09fWMa2rG/2dpIyThJ8Sf/ZRzH+uFCXjXZxHRDjD6vD0YOmKHNbxwPBGR5H/JplFsfA="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi