appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: C0lz3vJGgi6vpia/5QTBIKRlNRECW+xYA8swd88NMeYHUapmW+C23UhJ7xMVJlMhxuLUus/l9gnk01DpARmfGNCgCjdoOV2eTPQTEdGqqdXIE6ewhYMvCSc31kena+1HrXZEao3T0TDQdcV310lZOzipC1Nk4RviyRox4BvNdS4I66xiUTjhUp2PeOW7zJsoI3Bt3pZqd6OC9xqeBS3Fd9hKxYv3ynjkITvtkpv4Ra22wBHb0ROl49wYa02goBJ2qxmHT/igItuWfPy8Q+B2wew/mscnkus4+pS/ntfwYnQTeLUEpjH3dKAEl/I8vhsiWFkyc9ymusYz8R4rbZWllWrLkrG2QHvMm414Niw+Lwbe9CO5A1o3bm/xLMDtMPLZ6Rq4L+gx6nJf+5k5QR9HlVEKDnXcg5I0BelS0BUzOCUFGYWLcbAyi6aMkKIKWJi0Qi5S2FBs+faxO7c2iOk1Gb7U/2ZTNbg06J1ixBnsLuxPAWNSYEK0i9Z5i51SqmPLXoCa3vcufL9fsDrkO78fuwLb++N+YV454wx8MFMtL2bUAngBH7J4ju0tcj53m4bifVYxuXcxnAs69JK7EoUhboMH2KDuPLg5gT/3TsgN09fWMa2rG/2dpIyThJ8Sf/ZRzH+uFCXjXZxHRDjD6vD0YOmKHNbxwPBGR5H/JplFsfA=}
