travis:
  secure:
    BINSTAR_TOKEN: opo/D+tbZZ9MQ8DOCNgOkPe+9EwmII1w9sAjEVw8+GHMaMOxVeEKRbZMR1rLCxqpry5vCqbEYiuoNGdMCK/JWcOtPwM+9B7NNFUj2bgB/LOyl84appF8KgSgUhHIRprj8KFlhdQ75aJZY8vmHcxVCdKpy8wdSPR5XY6jjVIIqdk0oK3jacc2CPtsG7sDIeGgNBFomtDDLf5+eGYpXAnN3aEK+F0WIkp306c7br4onFLN3HnfXxO36k7Oeh9RWd0lODIRbHpQmuEgNY8ZH8kJe1clUrZNPiPtX4YupY/IhRK0w5XdpE2ZLkE3fvDd77sSr6MfJyL6ORabAGbOS6lF63MhwQunxACL7pKtcVh0gCXRv6NLch7a5yZ3zbtkoSOQryAXGfsBS9Gq4YzwjbtO2OMrzE+Frvwf3UpJpHMr9iMxb6MQD0/qBrKYQEd2+uocFHA9rLKXPPXunFBXOPzk8SUQgavmQstDieLQUj/JUrtGGKIHoFb1uhihgNVvk5JTBGSBr/fMKX/SmVVC+kxq/8+9brQGvOU5izpFe1UJel2i/vuLwiziyFtwMSYSMrVTx6tKpJrP9ngQ1EfPwM0uoCDOxtGFOAlUtm3tW/y4OwGws0XyCRY6nnIRR6SpRbCzOjgjpfLjI2BuyUVWeSsKw4QFjRUGA7uU+DPYYpjecAY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
